#!/usr/bin/env python3
"""verify_installer_artifacts.py
Canonical local gate for installer artifacts produced by build_installer_staging.py.

This script resolves the EXE and ZIP generated by the staging builder, derives a
verification manifest from the ZIP itself, writes a coherent latest.yml for the
EXE, and delegates the actual checks to scripts.verify_release.run_checks.
"""
from __future__ import annotations

import hashlib
import json
import os
import sys
import zipfile
from pathlib import Path
from tempfile import TemporaryDirectory

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from bago_core.versioning import read_release_version
from scripts.verify_release import (
    EXE_NAME,
    ZIP_NAME,
    _sha256_file,
    _sha512_file_b64,
    run_checks,
)


def _artifact_dir() -> Path:
    env = os.environ.get("BAGO_INSTALLER_ARTIFACTS")
    if env:
        return Path(env).resolve()
    dist = ROOT / "dist"
    if (dist / ZIP_NAME).exists():
        return dist
    installer_dist = dist / "installer"
    if (installer_dist / EXE_NAME).exists():
        return installer_dist
    raise RuntimeError(
        "No se encontraron artefactos del instalador. Define BAGO_INSTALLER_ARTIFACTS "
        f"o asegura que existen {dist / ZIP_NAME} o {installer_dist / EXE_NAME}."
    )


def _find_paths(artifacts: Path):
    exe_path = artifacts / "installer" / EXE_NAME
    if not exe_path.exists():
        exe_path = artifacts / EXE_NAME
    zip_path = artifacts / ZIP_NAME
    if not zip_path.exists() and artifacts.name == "installer":
        zip_path = artifacts.parent / ZIP_NAME
    return exe_path, zip_path


def _derive_manifest(zip_path: Path) -> dict:
    entries = []
    with zipfile.ZipFile(zip_path, "r") as zf:
        for info in zf.infolist():
            if info.is_dir():
                continue
            with zf.open(info) as handle:
                digest = hashlib.sha256()
                for chunk in iter(lambda: handle.read(1 << 16), b""):
                    digest.update(chunk)
            entries.append({
                "path": info.filename,
                "size": info.file_size,
                "sha256": digest.hexdigest(),
            })
    return {
        "package": ZIP_NAME,
        "file_count": len(entries),
        "zip_sha256": _sha256_file(zip_path),
        "included_files": entries,
        "excluded_prefixes": [],
        "forbidden_names": [],
    }


def _derive_latest_yml(exe_path: Path, version: str) -> str:
    return "\n".join([
        f"version: {version}",
        f"path: {EXE_NAME}",
        f"size: {exe_path.stat().st_size}",
        f"sha512: {_sha512_file_b64(exe_path)}",
    ]) + "\n"


def main(argv: list[str] | None = None) -> int:
    version = read_release_version(ROOT).strip()
    artifacts = _artifact_dir()
    exe_path, zip_path = _find_paths(artifacts)

    if not exe_path.exists():
        print(f"[FAIL] EXE no encontrado: {exe_path}", file=sys.stderr)
        return 2
    if not zip_path.exists():
        print(f"[FAIL] ZIP no encontrado: {zip_path}", file=sys.stderr)
        return 2

    with TemporaryDirectory(prefix="bago-artifacts-verify-") as td:
        tmp = Path(td)
        manifest_path = tmp / f"{ZIP_NAME}.manifest.json"
        zip_sha256_path = tmp / f"{ZIP_NAME}.sha256"
        latest_yml_path = tmp / "latest.yml"

        manifest = _derive_manifest(zip_path)
        manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
        zip_sha256_path.write_text(f"{manifest['zip_sha256']}  {ZIP_NAME}\n", encoding="utf-8")
        latest_yml_path.write_text(_derive_latest_yml(exe_path, version), encoding="utf-8")

        return run_checks(
            exe_path=exe_path,
            zip_path=zip_path,
            manifest_path=manifest_path,
            zip_sha256_path=zip_sha256_path,
            latest_yml_path=latest_yml_path,
        )


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
