"""Render the evidence-based semantic matrix; classification is reviewed manually."""
from pathlib import Path
import csv
import html
import json
from collections import Counter

OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[2]
rows=[]
def row(id,name,classification,scope,history,owner,route,source,tests,change,intent='NOT_ESTABLISHED',evidence='SOURCE_TRACED',equivalence='SCOPED'):
    rows.append(dict(id=id,capability=name,classification=classification,classification_scope=scope,historical_evidence=history,owner=owner,route=route,current_source=source,test_paths=tests,comparison=change,intent=intent,evidence=evidence,equivalence=equivalence))

row('C01','Estado de sesión','EXTENDED','Contrato de consulta', ['v4.0.0-mvp:.bago/core/session.py:12','v4.5.0:.bago/api/bridge.py:253','v4.8.0:backend/.bago/core/session_manager.py:102'],'SessionManager','GET /session; /status; /session','backend/.bago/api/handlers_session.py:20',['backend/tests/test_session_recovery_contract.py'],'La consulta conserva identidad/provider/model y añade binding de workspace, conversaciones y contrato. No se ha probado migración del active.json del MVP.')
row('C02','Guardar, cargar y recuperar sesión','EXTENDED','Persistencia y binding',['v4.5.0:.bago/chat/commands.py::cmd_save/cmd_load'],'SessionManager + ContextStore','/save; /load; sesiones API','backend/.bago/chat/commands.py:398',['backend/tests/test_chat_command_load_workspace.py','backend/tests/test_session_recovery_contract.py'],'La restauración usa project_root duradero; el backend conserva autoridad sobre la activación.')
row('C03','Chat y streaming','EXTENDED','Superficie HTTP y control del turno',['v4.5.0:.bago/api/bridge.py:368'],'SessionManager.send + chat_turns','POST /chat; POST /chat/stream','backend/.bago/api/handlers_chat.py:115',['backend/tests/test_chat_turn_idempotency.py'],'Se conserva chat y se añaden streaming e identidad/reintentos del turno. Test actual no presente en v4.11.10.')
row('C04','Cambiar proveedor/modelo','PRESERVED','Propósito y delegación al owner',['v4.5.0:.bago/api/bridge.py:450'],'SwitchEngine','POST /switch; /switch; /models','backend/.bago/api/handlers_switch.py:20',['backend/tests/test_session_recovery_contract.py'],'La ruta mantiene el cambio mediante SwitchEngine; equivalencia total de validaciones no ejecutada.')
row('C05','Comandos por HTTP','REPLACED','Ruta con alias de compatibilidad',['v4.5.0:.bago/api/bridge.py:413','v4.8.0:backend/contracts/api_routes.generated.json'],'chat.commands.execute','POST /command → /api/v1/commands','backend/.bago/api/legacy_aliases.py:55',['backend/tests/test_sprint_4_surfaces.py'],'Alias explícito conserva el acceso. La carga del módulo distingue chat.commands de bago_core.commands.','EXPLICIT_COMPATIBILITY_ALIAS')
row('C06','Workspace y operaciones de proyecto','REPLACED','Rutas antiguas, owner actual gobernado',['v4.8.0:backend/contracts/api_routes.generated.json'],'handlers_workspace / ProjectWriteEffectAdapter','/workspaces → /workspace/list; /workspace/{init,link,seed,sync} → /project/*','backend/.bago/api/legacy_aliases.py:49',['backend/tests/test_workspace_seed_contract.py'],'Las rutas antiguas tienen alias. Las mutaciones actuales añaden autorización; no es una pérdida por renombrado.','EXPLICIT_ALIAS_AND_AUTHORIZATION')
row('C07','Historial y conversaciones','EXTENDED','Persistencia por conversación',['v4.5.0:.bago/api/bridge.py:268','v4.9.0:backend/tests/test_conversation_contract.py'],'ContextStore','GET /history; /conversations; /workspace/conversation','backend/.bago/api/handlers_conversations.py:15',['backend/tests/test_conversation_contract.py'],'El historial se amplía con conversaciones, archivo y scope de workspace; el test conserva migración legacy→main.')
row('C08','Escribir archivos desde API','RESTRICTED','Autorización antes del efecto',['v4.8.0:backend/.bago/api/handlers_files.py:375','v4.11.0:backend/.bago/api/handlers_files.py:400'],'ExecutionGateway / owner de archivos','POST /files/write','backend/.bago/api/handlers_files.py:400',['backend/tests/test_files_write_workspace_scope.py'],'La escritura directa se sustituye por efecto gobernado y fallo cerrado sin Permit.','EXPLICIT_SECURITY_CONTRACT')
row('C09','Ejecutar planes materiales','RESTRICTED','Significado de ejecución exitosa',['v4.8.0:backend/.bago/core/plan_engine.py::execute_plan','v4.9.0:backend/.bago/api/handlers_jobs.py:306'],'PlanEngine + ExecutionGateway','POST /plans/<id>/execute','backend/.bago/core/plan_engine.py:224',['backend/tests/test_plan_engine_contract.py'],'Antes podían completarse pasos informativos o conversación run_command. Ahora el executor requiere executed, evidencia y receipt_id.','EXPLICIT_TRUTH_CONTRACT')
row('C10','Autopilot: texto considerado evidencia','PRESERVED','Debilidad semántica histórica; no preservación correcta',['v4.5.0:.bago/chat/commands.py::cmd_autopilot'],'chat.commands.cmd_autopilot','/autopilot','backend/.bago/chat/commands.py:976',['backend/tests/test_plan_engine_contract.py'],'El handler sigue tratando texto del modelo como ejecución. Probe con PlanEngine real: done y receipt_id vacío; respuesta vacía deja blocked con ok=true. El test citado cubre el motor, no directamente este handler.','NO_FIX_IN_THIS_AUDIT','FUNCTION_BOUNDARY_REPRODUCED')
row('C11','Límite de 20 pasos de autopilot','LOST','Garantía del handler al comparar snapshots',['v4.5.0:.bago/chat/commands.py::cmd_autopilot (max_steps=20)'],'chat.commands.cmd_autopilot','/autopilot','backend/.bago/chat/commands.py:991',['backend/tests/test_plan_engine_contract.py'],'Con 25 pasos, el handler antiguo hace 21 llamadas al stub (plan+20); el actual hace 26 (plan+25). No se atribuye a un commit de retirada ni se confunde rama histórica con ancestro.','NOT_ESTABLISHED','FUNCTION_BOUNDARY_REPRODUCED')
row('C12','Ciclo spawn/list/run/kill de agentes','REPLACED','Cambio de owner con compatibilidad rota o sin migración demostrada',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_agent','4aa0eb66:backend/bago_core/commands/cmd_tools.py'],'spiral_agent + agent_kit_cli','bago agent spawn/list/run/kill','backend/bago_core/commands/cmd_tools.py:147',['backend/tests/test_orchestration_tools.py'],'4aa0eb66 redirige list/run/describe/plan al kit, mientras spawn/kill/status siguen en spiral_agent. Requiere probar continuidad de identidad entre registros.','EXPLICIT_REPLACEMENT_COMPATIBILITY_INTENT_UNKNOWN')
row('C13','Navegador persistente y snapshot DOM','LOST','Interfaz REPL /browser y controller histórico; sustitución conceptual pendiente',['v4.5.0:.bago/chat/commands.py::cmd_browser','45e0b4d9 (introducción de Playwright persistente)'],'Owner actual equivalente no localizado','Histórico /browser open/snapshot/click/fill/eval; sin registro actual','backend/.bago/chat/commands.py:1153',[],'La fuente histórica despacha un controller Playwright. El registro actual carece de /browser. Los smokes DOM y browse de directorios no prueban sustitución equivalente. No se ha demostrado funcionamiento histórico en vivo.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_REPLACEMENT')
row('C14','Node Control','EXTENDED','Nodos, instalaciones, piezas y conectores',['v4.0.0-mvp:.bago/core/cli.py::cmd_nodes','v4.8.0:backend/bago_core/node_control_cli.py'],'Node Control','bago node status/validate/pieces/connect/disconnect/set-mode','backend/bago_core/node_control_cli.py:102',['backend/tests/test_node_control_split.py'],'Las operaciones actuales añaden identidad instalación/pieza y modos. No hay prueba de que el catálogo de capabilities haya reemplazado Node Control.')
row('C15','Evidencia de trabajo','REPLACED','Evolución de formato y autoridad',['v4.0.0-mvp:.bago/core/cli.py::cmd_evidence','v4.5.0:bago_core/launcher.py'],'Evidence bundles / claim ledger / receipts','bago evidence; bago claim; node evidence','backend/bago_core/evidence_cli.py:83',[],'La palabra evidence abarca owners y contratos distintos del índice MVP. Una cadena textual histórica no equivale a un receipt material actual.','DOCUMENTED_CONTRACT_EVOLUTION')
row('C16','RL shadow, entrenamiento y evaluación','EXTENDED','Observación y aprendizaje sin autoridad de ejecución',['v4.5.0:.bago/api/bridge.py:518','v4.9.0:backend/tests/test_rl_contract.py'],'RLBridge + rl_policies','/rl/status; /rl/shadow; train/eval','backend/.bago/api/handlers_rl.py:33',['backend/tests/test_rl_contract.py'],'Se conserva can_execute=False. Entrenamiento y evaluación amplían observación; no conceden ejecución autónoma.','EXPLICIT_SHADOW_BOUNDARY')
row('C17','Memoria y KB','EXTENDED','Dos servicios con contratos propios',['v4.8.0:backend/contracts/api_routes.generated.json','v4.10.0:backend/contracts/api_routes.generated.json'],'handlers_memory + handlers_kv','/memory/*; /api/v1/kb','backend/.bago/api/handlers_memory.py:17',['backend/tests/test_kv_integration_contract.py'],'Memoria añade búsqueda/embeddings; KB mantiene identidad propia. Mutaciones actuales usan autorización. No es el catálogo de capabilities.')
row('C18','Capability packages y pipelines ejecutables','EXTENDED','Contrato ZIP + entrada ejecutable',['v4.8.2:backend/.bago/core/capability_packages.py:1'],'CapabilityPackageImportEffectAdapter + ExecutionGateway','/api/v1/capability-packages/*','backend/.bago/core/capability_packages.py:584',['backend/tests/test_capability_packages.py','backend/tests/test_capability_import_gateway.py'],'Primera presencia entre tags locales seleccionados: v4.8.2, ausente en v4.8.0/.1. Ya exigía confirmación y receipt. Gobierno posterior amplía/restringe ejecución. Precede al inventario read_only observado en v4.9.0.','EXPLICIT_PACKAGE_CONTRACT')
row('C19','Capability de inventario read_only','PRESERVED','bago-runtime-inventory, no censo de todo el producto',['v4.9.0:backend/.bago/api/capability_contract.py:20'],'capability_contract','GET /api/v1/capabilities','backend/.bago/api/capability_contract.py:90',['backend/tests/test_capability_contract.py'],'Sin diff en capability_contract.py entre v4.9.0 y HEAD. Una capability de inventario no enumera toda la capacidad histórica del Framework.','EXPLICIT_READ_ONLY_CONTRACT')
row('C20','Schedules y delegación','RESTRICTED','Autorización de ejecuciones diferidas',['v4.9.0:backend/tests/test_schedule_registry.py'],'schedule_registry + ExecutionGateway','/schedule/*','backend/.bago/api/handlers_schedule.py:271',['backend/tests/test_schedule_registry.py','backend/tests/test_schedule_delegation.py'],'La programación persiste; la ejecución requiere delegación/permiso actuales. Confirmación guardada no equivale a autoridad vigente.','EXPLICIT_DELEGATION_CONTRACT')
row('C21','Copilot como proveedor CLI','RESTRICTED','Transporte LLM y herramientas del proveedor',['v4.8.0:backend/.bago/providers/copilot.py:37'],'CopilotAdapter + cli_bridge','Provider chat mediante CLI','backend/.bago/providers/copilot.py:39',['backend/tests/test_cli_bridge_contract.py'],'El transporte existe; el test exige plan mode, denegar shell/write y desactivar MCP. No prueba integración BAGO como host Copilot.','EXPLICIT_PROVIDER_CONTRACT')
row('C22','Pi provider','PRESERVED','Fase 1 sin tools, desactivada por defecto',['v4.8.0:backend/.bago/integrations/pi/provider_adapter.py:224'],'BagoPiProviderAdapter','Provider adapter (habilitación no probada)','backend/.bago/integrations/pi/provider_adapter.py:224',[],'El adapter se conserva sin diff; disponibilidad de Pi en esta máquina no comprobada.','EXPLICIT_PHASE1_BOUNDARY')
row('C23','Pi ejecutor delegado','EXTENDED','Contrato de ejecución separado del provider',['v4.8.0:backend/.bago/integrations/pi/agent_runner.py'],'Pi AgentRunner','Agent runner Fase 3','backend/.bago/integrations/pi/agent_runner.py:71',['backend/tests/integrations/pi/test_agent_runner.py'],'Provider y runner ya coexistían. Digest, revisión y pi_finished forman parte del contrato; IO/proceso han evolucionado.','EXPLICIT_PHASE3_BOUNDARY')
row('C24','Taxonomía rol/workflow/sesión','PRESERVED','Contrato documental, runtime no reconstruido por completo',['v3.5.0:.bago/core/canon/TAXONOMIA.md'],'Canon + role_factory','Contratos de rol y workflow','backend/.bago/core/canon/TAXONOMIA.md',[],'El vocabulario continúa; estados de pipeline se añaden de forma separada. Capability package no ha borrado la taxonomía.','EXPLICIT_TAXONOMY','DOCUMENT_CONTRACT_ONLY')
row('C25','Control headless de sesiones','REPLACED','Alias CLI retirado, módulo alternativo conservado',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_session'],'bago_core.session_control','Antes bago session; ahora módulo session_control','backend/bago_core/session_control.py:162',['backend/tests/test_session_recovery_contract.py'],'El alias top-level desaparece; módulo list/create/etc permanece. Compatibilidad de invocación CLI requiere decisión explícita.')
row('C26','Workflow/orquestación','REPLACED','Interfaz y modelo de workflow; equivalencia incompleta',['v3.2-kernel:.bago/tools/tool_registry.py','v4.5.0:bago_core/launcher.py'],'orchestrator_v4','bago orchestrate; /orchestrate','backend/bago_core/launcher.py:118',['backend/tests/test_orchestration_tools.py'],'El workflow selector v3 y los task briefs actuales representan modelos distintos. No se da por preservado todo el contrato v3.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_EQUIVALENCE')
row('C27','issues-gh anunciado por el parser','PRESERVED','Defecto histórico, no capacidad funcional probada',['v4.5.0:bago_core/parsers_sections.py (issues-gh)','v4.5.0:bago_core/launcher.py (sin dispatch)'],'Sin handler en dispatcher','bago issues-gh take','backend/bago_core/parsers_sections.py:374',[],'El parser lo acepta, _DISPATCH_TABLE lo omite y _dispatch imprime ayuda y devuelve 0. Probe reproduce el retorno. No se clasifica LOST porque el defecto ya existía.','NOT_ESTABLISHED','FUNCTION_BOUNDARY_REPRODUCED')
row('C28','Mutaciones GitHub por HTTP','RESTRICTED','Facades antiguas devuelven 410',['v4.8.7:backend/.bago/api/handlers_github.py:506'],'Desktop/process authorization; owner process','POST /github/setup-git → /github/setup','backend/.bago/api/handlers_github.py:325',['backend/tests/test_github_api_contract.py'],'El alias sigue, pero setup devuelve 410 intencionalmente. process admite git_identity; flujo completo UI alternativo no ejecutado. v4.8.7 es rama no ancestral.','EXPLICIT_FAIL_CLOSED_TEST')
row('C29','Cancelación de interpretación histórica','REPLACED','Corrección de alias semánticamente falso',['v4.9.0:backend/.bago/api/legacy_aliases.py:70','v4.10.0:backend/.bago/api/legacy_aliases.py:70','fa3f2d3c (corrige el alias)'],'handlers_interpret','Antes POST /interpretations/{id}/cancel → /interpret; alias retirado','backend/.bago/api/legacy_aliases.py:66',[],'Cancelar invocaba interpretar de nuevo. Corregido antes de v4.11.0. No demuestra que hubiese una cancelación funcional perdida.','EXPLICIT_BUG_FIX')
row('C30','Detalle de interpretación por ID','PRESERVED','Incompatibilidad residual entre alias y cliente',['v4.9.0:backend/.bago/api/legacy_aliases.py'],'handlers_interpret + API client','GET /interpretations/{id} → /interpret/history','backend/.bago/api/legacy_aliases.py:72',[],'El handler devuelve colección y no consulta ID; client.ts:721 espera objeto individual. Sin callsites UI encontrados: impacto visible no demostrado.','NOT_ESTABLISHED')
row('C31','Prompt del rol crece por ciclo','LOST','Implementación exacta RoleSpiralBuilder; concepto por resolver',['v3.5.0:.bago/tools/role_embedded.py:53','v3.5.0:tests/test_v35_features.py:62'],'No equivalente demostrado; SpiralAgent actual rota pasos','Histórico RoleSpiralBuilder','backend/.bago/tools/spiral_agent.py:279',[],'No hay símbolos spiral_index/RoleSpiralBuilder en backend rastreado. No hay ancestro común local entre v3.5.0 y HEAD: no se atribuye una eliminación accidental.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_REPLACEMENT')
row('C32','Selección adaptativa band/channel/hz','LOST','Implementación SignalMetrics; concepto por resolver',['v3.5.0:.bago/core/prompt_router.py:21','v3.5.0:tests/test_v35_features.py:17'],'No equivalente demostrado','Histórico SignalMetrics.band/channel/hz','backend/bago_core/providers/routing.py',[],'El router actual de modelos no demuestra selección por deriva/presión/coherencia del prompt. La rama v3.5.0 está desconectada del HEAD local.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_REPLACEMENT')
row('C33','ModelGate direct/fallback/degrade','REPLACED','Reemplazo conceptual parcial; garantías sin equivalencia probada',['v3.5.0:.bago/tools/model_gate.py','v3.5.0:tests/test_v35_features.py:108'],'session_adapters_mixin + repl_model_router','Selección/fallback de modelo','backend/.bago/core/session_adapters_mixin.py:118',['backend/tests/test_router_session_model.py'],'Existe fallback dentro del proveedor y auto-switch. Falta equivalencia demostrada de FALLBACK_CHAIN entre providers y los resultados direct/fallback/degrade.','NOT_ESTABLISHED','SOURCE_TRACED','PARTIAL_REPLACEMENT')

row('C34','Familia CLI autonomous','LOST','Interfaz pública completa; comportamientos parciales conservados',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_autonomous'],'autonomous_loop / repl_startup / comandos de sesión','Histórico bago autonomous; actuales /evolve, /autopilot y módulo autonomous_loop','backend/.bago/core/autonomous_loop.py:801',[],'Desaparece la familia CLI. Startup evolution y loop sobreviven, con autorización para herramientas mutantes. /autopilot no equivale a todas las operaciones anteriores.','NOT_ESTABLISHED','SOURCE_TRACED','PARTIAL_REPLACEMENT')
row('C35','Registro de workspaces con nombre por CLI','LOST','Interfaz named add/remove/select/list/status',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_workspace'],'Project/workspace binding actual','Histórico bago workspace; actuales /workspace/* y picker','backend/.bago/api/api_dispatch.py:60',[],'workspace_registry.py histórico no localizado actualmente. Picker y binding existen; equivalencia con registro multi-workspace con nombre no demostrada.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_REPLACEMENT')
row('C36','Federación de conocimiento por CLI','LOST','Interfaz knowledge source-list/add/remove/pull/pull-all',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_knowledge'],'Sin owner actual de federación identificado','Histórico bago knowledge','backend/.bago/chat/memory_commands.py',[],'knowledge_federation.py no localizado en backend actual. La memoria local no demuestra federación de fuentes remotas.','NOT_ESTABLISHED','SOURCE_TRACED','UNRESOLVED_CONCEPTUAL_REPLACEMENT')
row('C37','Arrancar host C++ de referencia','LOST','Launcher cpp-runtime; el adapter cliente permanece',['v4.5.0:bago_core/commands/cmd_system.py::cmd_cpp_runtime','fa949059 (parser retira cpp-runtime frente al padre)'],'CppLocalAdapter cliente HTTP','Histórico bago cpp-runtime; provider cpp-local conservado','backend/.bago/providers/cpp_local.py:49',[],'cpp_runtime_host no localizado. cpp-local sigue como cliente configurable; no se declara perdido todo el provider.','REMOVAL_COMMIT_IDENTIFIED_INTENT_UNRESOLVED')
row('C38','Administrar chains desde terminal','LOST','Interfaz CLI; persistencia Electron conservada',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_chain'],'Electron manager settings / chain_registry','Histórico bago chain; bridge read/write chains.json','backend/electron/preload.cjs:171',[],'Electron mantiene registry de chains y escritura gobernada. No se demostró paridad de todos los subcomandos list/show/import/export/validate/stage/step.','NOT_ESTABLISHED','SOURCE_TRACED','PARTIAL_REPLACEMENT')
row('C39','Release jobs headless por CLI','LOST','Interfaz de terminal; operaciones de release conservadas en otras superficies',['v4.5.0:bago_core/commands/cmd_tools.py::cmd_release_job'],'Electron release service + gateway','Histórico bago release-job; IPC list/preflight/start/cancel/resume/install/rollback','backend/electron/ipc-service.cjs:61',[],'El script release-job-cli.cjs desaparece. Manager/IPC y rutas backend mantienen operaciones; no se declara perdido el subsistema de release.','NOT_ESTABLISHED','SOURCE_TRACED','PARTIAL_REPLACEMENT')

findings=[
 dict(id='S01',priority='HIGH',title='Agent: mismo nombre de familia, dos registros',capabilities=['C12'],status='CONFIRMED_DISPATCH_SPLIT',history='4aa0eb66 añade la interceptación list/run/describe/plan; spawn/kill/status siguen en spiral_agent.',impact='Un agente creado por spawn no tiene continuidad de identidad demostrada hacia list/run.',accidental='CANDIDATE; intención de migración no demostrada',verification='Probar spawn → list → run → kill con la misma identidad; exigir migración o namespaces explícitos.'),
 dict(id='S02',priority='HIGH',title='Autopilot convierte prosa en done',capabilities=['C10'],status='FUNCTION_BOUNDARY_REPRODUCED',history='Debilidad presente en v4.5.0; persiste tras introducir vocabulario de evidencia.',impact='done sin receipt material, en contradicción con execute_plan; blocked también devuelve ok=true.',accidental='NO_NEW_OVERWRITE_PROVEN; inconsistencia actual confirmada',verification='Unificar el criterio de ejecución del handler y motor; negativo con solo texto y sin receipt.'),
 dict(id='S03',priority='HIGH',title='Autopilot sin límite histórico de 20 pasos',capabilities=['C11'],status='FUNCTION_BOUNDARY_REPRODUCED',history='v4.5.0 limita a 20; snapshot actual recorre todos los pasos.',impact='El probe de 25 pasos produce 25 llamadas de ejecución simulada frente a 20 históricas.',accidental='CANDIDATE; no commit de retirada ni intención atribuidos',verification='Decidir el límite actual y probar cancelación, error y corte; no restaurar automáticamente una política histórica.'),
 dict(id='S04',priority='MEDIUM',title='issues-gh: comando aceptado, salida 0 sin handler',capabilities=['C27'],status='FUNCTION_BOUNDARY_REPRODUCED',history='Presente también en v4.5.0.',impact='Un consumidor puede interpretar éxito aunque solo se imprimió ayuda.',accidental='HISTORICAL_DEFECT_PRESERVED',verification='Conformidad parser↔dispatcher y código de error para rutas sin implementación.'),
 dict(id='S05',priority='MEDIUM',title='Interpretación por ID devuelve colección',capabilities=['C30'],status='SOURCE_TRACED',history='Alias actual reenvía a history; cliente espera InterpretationResult.',impact='Contrato cliente/API incoherente. Callsite UI no encontrado; impacto runtime no probado.',accidental='CANDIDATE; intención no establecida',verification='Contrato de detalle por ID o retirada explícita del método; probar que el ID se usa.'),
 dict(id='S06',priority='HISTORICAL_FIXED',title='Cancelar interpretación creaba otra interpretación',capabilities=['C29'],status='CORRECTED_BY_fa3f2d3c',history='v4.9/v4.10 alias cancel→interpret; retirado antes de v4.11.0.',impact='Sobrescritura semántica histórica confirmada y corregida; no es una cancelación funcional perdida.',accidental='EXPLICIT_BUG_FIX',verification='Mantener negativa de que cancelar no invoca interpretar; reconciliar método residual del cliente.'),
 dict(id='S07',priority='DESIGN_GATE',title='Inventario read_only confundido con todas las capacidades',capabilities=['C18','C19','C24'],status='INTERPRETATION_RISK_NOT_CODE_OVERWRITE',history='Paquetes ejecutables aparecen en v4.8.2; inventario observado en v4.9.0 coexiste con roles/workflows.',impact='Usar un solo endpoint como catálogo del Framework omitiría capacidades históricas reales.',accidental='NO_CODE_OVERWRITE_PROVEN',verification='Mantener IDs semánticos y distinguir provider, host, paquete, rol, workflow e inventario.'),
]

versions=json.loads((OUT/'versions.json').read_text(encoding='utf-8'))
tests=json.loads((OUT/'test-history.json').read_text(encoding='utf-8'))
coverage=json.loads((OUT/'coverage.json').read_text(encoding='utf-8'))
freeze=json.loads((OUT/'freeze-before.json').read_text(encoding='utf-8'))
for r in rows:
    names={Path(p).name for p in r['test_paths']}
    r['historical_test_file_presence']=[t for t in tests if t['version'] not in ('HEAD','WORKTREE') and Path(t['path']).name in names]
    r['test_results']='SOURCE_READ_NOT_RUN; controlled probes are separate'
    r['historical_test_link_limit']='Filename/blob presence is not identical assertion semantics nor a passing test result.'
    r['source_current_exists']=(ROOT/r['current_source'].split(':')[0]).exists()
data={'schema':'bago.capability-lineage.v1','status':'AUDIT_EXECUTED_SCOPED','candidate_head':freeze['head'],'surface_sha256':freeze['surface_sha256'],'classification_rule':'Exactly one primary classification per row, scoped explicitly. LOST interface/implementation does not assert whole-product loss; preserved defects remain defects. Accidental intent is separate.','capabilities':rows,'findings':findings,'coverage':coverage,'versions':versions,'pending':['Live execution of each public route and external CLI host is NOT_RUN.','Legacy registry/inline surfaces before ROUTE_META have manual family traces, not exhaustive automatic enumeration.','Conceptual replacement for v3 prompt-cycle and SignalMetrics remains unresolved.','All local tags inspected as objects; remote publication state is outside this audit.','Migration of old saved state formats and full v3 workflow semantics not demonstrated.']}
(OUT/'capability-matrix.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
with (OUT/'capability-matrix.csv').open('w',encoding='utf-8-sig',newline='') as f:
    writer=csv.writer(f);writer.writerow(['id','capability','classification','scope','history','owner','route','current_source','tests','comparison','intent','evidence'])
    for r in rows:writer.writerow([r['id'],r['capability'],r['classification'],r['classification_scope'],' | '.join(r['historical_evidence']),r['owner'],r['route'],r['current_source'],' | '.join(r['test_paths']),r['comparison'],r['intent'],r['evidence']])
counts=Counter(r['classification'] for r in rows)
md=['# BAGO · Auditoría histórica de capacidades','',f"Candidato `{freeze['head']}`; versión de checkout `{freeze['version']}`; árbol dirty preservado.",'',f"Freeze lógico: `{freeze['surface_sha256']}`; {len(freeze['manifest'])} archivos rastreados o fuentes nuevas relevantes. El alcance y exclusiones están en freeze-before.json.",'',f"{coverage['local_version_tags']} tags locales inspeccionados; {coverage['route_metadata_tags']} con ROUTE_META extraíble; {coverage['current_routes']} pares método+ruta únicos actuales. No equivalen a número de capacidades.",'','La matriz contiene familias trazadas manualmente. La reconstrucción semántica global permanece parcial donde se indica equivalencia pendiente; ninguna fila certifica runtime por presencia de fuente.','',f'Clasificaciones de las filas: {dict(counts)}.','', '## Hallazgos','']
for x in findings:md += [f"### {x['id']} · {x['title']}",'',x['history'], '',x['impact'],'',f"Estado: `{x['status']}`. Accidentalidad: {x['accidental']}.",'',f"Verificación propuesta: {x['verification']}",'']
md+=['## Matriz','', '| ID | Capacidad | Clasificación | Owner / ruta | Evidencia |','|---|---|---|---|---|']
for r in rows:md.append(f"| {r['id']} | {r['capability']} | {r['classification']} ({r['classification_scope']}) | {r['owner']} · {r['route']} | {r['current_source']} |")
md += ['', '## Límites y puerta previa a la separación del Framework','',*['- '+s for s in data['pending']],'','La siguiente fase debe resolver continuidad agent spawn/list/run, semántica autopilot y pérdidas históricas por interfaz antes de mover owners. Los probes de DOM históricos deben revisarse como antecedentes; no se reactivan por encontrar su código.','', 'Reproducción: `python collect.py freeze` solo crea el freeze inicial; `python collect.py collect`, `python probe_semantics.py`, `python collect.py check`, `python build_report.py`. Ejecutar desde este directorio o pasar la ruta completa. No sobrescribir el freeze original.','']
(OUT/'REPORT.md').write_text('\n'.join(md),encoding='utf-8')
payload=json.dumps(data,ensure_ascii=False).replace('<','\\u003c')
page='''<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BAGO · Linaje de capacidades</title><style>
:root{font-family:Segoe UI,system-ui,sans-serif;color:#182938;background:#f3f6f9}*{box-sizing:border-box}body{margin:0}main{max-width:1450px;margin:auto;padding:28px}a{color:#2260ac}header{background:#142d46;color:#fff;padding:28px;border-radius:16px}header a{color:#c4dfff}h1{font-size:31px;margin:14px 0}p{line-height:1.55}.meta{font-size:12px;overflow-wrap:anywhere;color:#bed1e3}.stats{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0}.stat,section,aside{background:white;border:1px solid #dce4eb;border-radius:12px;padding:18px}.stat b{display:block;font-size:24px}.stat span{font-size:12px;color:#536879}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}input,select,button{font:inherit;padding:10px;border:1px solid #b9c8d4;border-radius:7px;background:white}input{flex:1;min-width:180px}button{cursor:pointer;color:#164b78}button:hover{background:#eef5ff}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #d88f28;outline-offset:3px}.grid{display:grid;grid-template-columns:minmax(0,1.8fr) minmax(280px,1fr);gap:16px}.tablewrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:12px;border-bottom:1px solid #e3eaf0;vertical-align:top}th{background:#eaf0f6}td small{display:block;color:#687888;margin-top:5px}.badge{font-size:10px;font-weight:800;border-radius:5px;padding:5px 7px;background:#e5eef9;white-space:nowrap}.LOST{background:#ffe4dc;color:#8a3020}.RESTRICTED{background:#fff0cd;color:#725019}.PRESERVED{background:#e2f2e9;color:#285c40}aside{align-self:start;position:sticky;top:12px}aside h2{margin-top:0}aside p,aside li{font-size:13px}code{font-size:12px;overflow-wrap:anywhere}aside ul{padding-left:20px}.note{border-left:4px solid #c8872d;padding:12px 18px;background:#fff6e6;margin:16px 0;border-radius:5px}.findings{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:12px;margin-top:20px}.finding h3{font-size:16px;margin:6px 0}.finding p{font-size:13px}.versions{max-height:320px;overflow:auto;margin-top:16px}footer{margin:24px 0;font-size:12px;color:#587082}@media(max-width:850px){.grid{grid-template-columns:1fr}aside{position:static}main{padding:14px}h1{font-size:25px}}</style>
<main><header><a href="../bago_mind_map.html">← Mapa mental</a> · <a href="../framework-cli-app-separation-plan.html">Plan Framework / CLI / App</a><h1>Linaje de capacidades BAGO</h1><p>Freeze → historia → owner → ruta → tests → comparación semántica.</p><div class="meta" id="identity"></div></header>
<div class="stats" id="stats"></div><div class="note"><b>Lectura de resultados:</b> LOST puede referirse a una interfaz o implementación concreta. La intención accidental se evalúa por separado. El listado de rutas no es el catálogo funcional completo. Tests citados ≠ tests ejecutados.</div>
<nav class="controls" aria-label="Filtrar capacidades"><input id="search" type="search" placeholder="Buscar capacidad, owner, versión o ruta" aria-label="Buscar capacidad"><select id="classification" aria-label="Clasificación"><option value="">Todas las clasificaciones</option><option>PRESERVED</option><option>EXTENDED</option><option>RESTRICTED</option><option>REPLACED</option><option>LOST</option></select><a href="capability-matrix.csv" download>CSV</a><a href="capability-matrix.json" download>JSON</a><a href="REPORT.md">Informe</a></nav>
<div class="grid"><section class="tablewrap"><p id="count" role="status"></p><table><thead><tr><th>Capacidad</th><th>Clasificación</th><th>Owner / ruta</th></tr></thead><tbody id="rows"></tbody></table></section><aside id="detail" aria-live="polite"></aside></div>
<h2>Sobrescrituras, regresiones y defectos conservados</h2><div class="findings" id="findings"></div>
<h2>Tags locales y genealogía</h2><p>El orden de versión no demuestra una cadena de ascendencia. Los tags divergentes o desconectados son antecedentes comparables; no prueban un commit de pérdida en la rama actual.</p><section class="versions"><table><thead><tr><th>Tag</th><th>Relación con HEAD</th><th>Rutas metadata</th><th>Tests fuente</th></tr></thead><tbody id="versions"></tbody></table></section>
<div class="note"><b>Cierre:</b> auditoría estática y probes de funciones ejecutados. Reconstrucción global parcial: faltan equivalencias semánticas indicadas y pruebas de runtime. La separación del Framework debe resolver estas diferencias antes de cambiar owners.</div>
<footer><a href="freeze-before.json">Freeze inicial</a> · <a href="freeze-check.json">Comprobación de freeze</a> · <a href="semantic-probes.json">Probes ejecutados</a> · <a href="current-routes.json">Superficie HTTP</a> · <a href="current-command-surface.json">Superficie CLI/REPL</a> · <a href="coverage.json">Cobertura</a></footer></main>
<script>const DATA=__DATA__;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.getElementById('identity').textContent=`HEAD ${DATA.candidate_head} · SHA256 superficie ${DATA.surface_sha256}`;
document.getElementById('stats').innerHTML=[[DATA.coverage.local_version_tags,'tags locales'],[DATA.coverage.current_routes,'rutas únicas actuales'],[DATA.capabilities.length,'familias trazadas'],[DATA.findings.length,'hallazgos / riesgos']].map(([n,t])=>`<div class="stat"><b>${n}</b><span>${t}</span></div>`).join('');
function select(id){const r=DATA.capabilities.find(x=>x.id===id);document.getElementById('detail').innerHTML=`<span class="badge ${r.classification}">${r.classification}</span><h2>${esc(r.id)} · ${esc(r.capability)}</h2><p><b>Alcance:</b> ${esc(r.classification_scope)}</p><p>${esc(r.comparison)}</p><p><b>Owner:</b> ${esc(r.owner)}</p><p><b>Ruta:</b> ${esc(r.route)}</p><p><b>Fuente actual:</b> <code>${esc(r.current_source)}</code></p><h3>Historia</h3><ul>${r.historical_evidence.map(x=>`<li><code>${esc(x)}</code></li>`).join('')}</ul><h3>Tests leídos / asociados</h3><ul>${r.test_paths.length?r.test_paths.map(x=>`<li><code>${esc(x)}</code></li>`).join(''):'<li>Sin test actual directo identificado; ver evidencia histórica.</li>'}</ul><p><b>Evidencia:</b> ${esc(r.evidence)}</p><p><b>Intención:</b> ${esc(r.intent)}</p><p><b>Equivalencia:</b> ${esc(r.equivalence)}</p>`}
function render(){let q=document.getElementById('search').value.toLowerCase(),c=document.getElementById('classification').value;const a=DATA.capabilities.filter(r=>(!c||r.classification===c)&&JSON.stringify(r).toLowerCase().includes(q));document.getElementById('count').textContent=`${a.length} de ${DATA.capabilities.length} familias`;document.getElementById('rows').innerHTML=a.map(r=>`<tr><td><button data-id="${r.id}">${esc(r.id)} · ${esc(r.capability)}</button><small>${esc(r.classification_scope)}</small></td><td><span class="badge ${r.classification}">${r.classification}</span></td><td>${esc(r.owner)}<small>${esc(r.route)}</small></td></tr>`).join('')}
document.getElementById('rows').addEventListener('click',e=>{let b=e.target.closest('button[data-id]');if(b)select(b.dataset.id)});document.getElementById('search').addEventListener('input',render);document.getElementById('classification').addEventListener('change',render);
document.getElementById('findings').innerHTML=DATA.findings.map(f=>`<section class="finding"><small>${esc(f.id)} · ${esc(f.priority)}</small><h3>${esc(f.title)}</h3><p>${esc(f.impact)}</p><p><b>${esc(f.status)}</b></p><p>${esc(f.accidental)}</p><p>${esc(f.verification)}</p></section>`).join('');
document.getElementById('versions').innerHTML=DATA.versions.filter(v=>!['HEAD','WORKTREE'].includes(v.ref)).map(v=>`<tr><td>${esc(v.ref)}<small>${esc(v.commit.slice(0,10))}</small></td><td>${esc(v.relationship_to_head)}</td><td>${v.routes||'Sin metadata; traza legacy'}</td><td>${v.test_files}</td></tr>`).join('');render();select('C12');</script></html>'''
(OUT/'index.html').write_text(page.replace('__DATA__',payload),encoding='utf-8')
print(json.dumps({'families':len(rows),'classifications':dict(counts),'missing_current_sources':[r['current_source'] for r in rows if not r['source_current_exists']],'status':data['status']},ensure_ascii=False))
