"""AC7: generated truth projections exist, carry provenance, and CI runs their drift checks."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ROUTES = ROOT / "backend" / "contracts" / "api_routes.generated.json"
IMPORT_INVENTORY = ROOT / "backend" / "contracts" / "import_migration_inventory.v1.json"
ROUTING_POLICY = ROOT / "backend" / "contracts" / "model_routing_policy.v1.json"
README_PROJECTION = ROOT / "backend" / "contracts" / "readme_projection.v1.json"
README = ROOT / "README.md"
CI = ROOT / ".github" / "workflows" / "canonical-ci.yml"
VALIDATE_EXPECTED = ROOT / ".github" / "workflows" / "validate-expected.yml"
GENERATOR = ROOT / "backend" / "scripts" / "generate_api_routes_contract.py"
README_GENERATOR = ROOT / "backend" / "scripts" / "generate_readme_projection.py"
PRE_COMMIT = ROOT / ".githooks" / "pre-commit"
PRE_PUSH = ROOT / ".githooks" / "pre-push"
HOOK_SETUP = ROOT / "backend" / "scripts" / "setup_git_hooks.ps1"
POSTINSTALL = ROOT / "scripts" / "postinstall.cjs"


def test_routes_projection_is_generated_from_canonical_dispatch() -> None:
    contract = json.loads(ROUTES.read_text(encoding="utf-8"))

    assert contract["source"] == "backend/.bago/api/api_dispatch.py"
    assert contract["routes"]
    assert all({"method", "path", "handler_module", "handler_fn"} <= set(route) for route in contract["routes"])
    # Dynamic routes come from DYNAMIC_ROUTE_META, not a hardcoded subset.
    assert len(contract["dynamic_routes"]) > 8
    dynamic_paths = {route["path"] for route in contract["dynamic_routes"]}
    assert "/api/v1/kb/<key>" in dynamic_paths
    assert "/api/v1/capability-packages/<capability_id>/execute" in dynamic_paths
    assert "/schedule/<schedule_id>" in dynamic_paths
    assert "DYNAMIC_ROUTE_META" in GENERATOR.read_text(encoding="utf-8")


def test_import_inventory_and_routing_policy_are_versioned_projections() -> None:
    inventory = json.loads(IMPORT_INVENTORY.read_text(encoding="utf-8"))
    policy = json.loads(ROUTING_POLICY.read_text(encoding="utf-8"))

    assert inventory["contract"] == "bago.import-migration-inventory.v1"
    assert inventory["total_files"] > 0
    assert inventory["generated_from"].startswith("AST scan")
    assert policy["contract"] == "bago.model-routing-policy.v1"
    assert policy["version"] == "1.0.0"
    assert policy["source"] == "repository-policy"


def test_readme_projection_is_versioned_and_bound_to_canonical_sources() -> None:
    projection = json.loads(README_PROJECTION.read_text(encoding="utf-8"))

    assert projection["contract"] == "bago.readme-projection.v1"
    assert projection["product"]["version"] == (ROOT / "release_version.txt").read_text(encoding="utf-8").strip()
    assert projection["product"]["node_engine"] == ">=22.12.0"
    assert projection["product"]["npm_engine"] == ">=10.0.0"
    assert projection["governance"]["effect_registry_status"] == "active"
    assert projection["governance"]["effect_count"] >= 27
    assert projection["governance"]["scheduler_delegation_status"] == "P4_IMPLEMENTED · RETEST_READY"
    assert projection["governance"]["unique_execution_boundary"] == "NOT_YET"
    assert projection["governance"]["strong_human_identity_verified"] == "NO"
    assert projection["governance"]["next_gateway_phase"].startswith("P5")
    assert "ollama-local" in projection["providers"]
    assert "openrouter" in projection["providers"]

    generated_from = set(projection["generated_from"])
    assert "release_version.txt" in generated_from
    assert "backend/.bago/contracts/bago.effect-registry.v1.json" in generated_from
    assert "backend/docs/contracts/scheduler_delegation.v1.md" in generated_from


def test_readme_contains_exactly_one_generated_truth_block() -> None:
    readme = README.read_text(encoding="utf-8")

    assert readme.count("<!-- BAGO:README_TRUTH:START -->") == 1
    assert readme.count("<!-- BAGO:README_TRUTH:END -->") == 1
    assert "Generated by backend/scripts/generate_readme_projection.py" in readme
    assert "P4_IMPLEMENTED · RETEST_READY" in readme
    assert "P5 — LLM Tool Calls" in readme
    assert "npm run docs:sync" in readme
    assert "npm run docs:check" in readme


def test_ci_runs_drift_checks_for_generated_projections() -> None:
    ci = CI.read_text(encoding="utf-8")

    assert "Check generated truth projections for drift" in ci
    assert "python backend/scripts/generate_api_routes_contract.py --check" in ci
    assert "python scripts/generate_readme_projection.py --check" in ci
    assert "python scripts/verify_readme_freshness.py" in ci
    assert "test_import_consolidation.py::test_migration_inventory_is_current_and_machine_checkable" in ci
    assert "test_version_drift.py" in ci
    # Drift checks must run after dependencies are installed.
    assert ci.index("Install dependencies") < ci.index("Check generated truth projections for drift")
    drift_block = ci[ci.index("Check generated truth projections"):ci.index("Build, typecheck")]
    assert "working-directory" not in drift_block


def test_validate_expected_also_blocks_readme_drift() -> None:
    workflow = VALIDATE_EXPECTED.read_text(encoding="utf-8")

    assert "Validate README truth projection" in workflow
    assert "python backend/scripts/generate_readme_projection.py --check" in workflow
    assert workflow.index("Validate canonical version consistency") < workflow.index("Validate README truth projection")


def test_routes_generator_supports_check_mode() -> None:
    source = GENERATOR.read_text(encoding="utf-8")

    assert '"--check"' in source
    assert "generated contract differs" in source


def test_import_inventory_generator_supports_check_mode() -> None:
    source = (ROOT / "backend" / "scripts" / "generate_import_migration_inventory.py").read_text(encoding="utf-8")

    assert '"--check"' in source
    assert "drift detected" in source
    assert "add_piece_paths" in source
    assert "sys.path" in source


def test_readme_generator_supports_write_and_check_modes() -> None:
    source = README_GENERATOR.read_text(encoding="utf-8")

    assert '"--check"' in source
    assert "README.md generated truth block drifted" in source
    assert "ADAPTER_REGISTRY" in source
    assert "bago.effect-registry.v1.json" in source
    assert "scheduler_delegation.v1.md" in source
    assert "execution_gateway_unification_plan.v1.md" in source


def test_repository_hooks_keep_readme_projection_synchronized() -> None:
    pre_commit = PRE_COMMIT.read_text(encoding="utf-8")
    pre_push = PRE_PUSH.read_text(encoding="utf-8")
    setup = HOOK_SETUP.read_text(encoding="utf-8")
    postinstall = POSTINSTALL.read_text(encoding="utf-8")
    package = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))

    assert "generate_readme_projection.py" in pre_commit
    assert "git add README.md backend/contracts/readme_projection.v1.json" in pre_commit
    assert "generate_readme_projection.py --check" in pre_commit
    assert "refs/heads/main" in pre_push
    assert "refs/heads/windows" in pre_push
    assert "refs/heads/android" in pre_push
    assert 'git config core.hooksPath ".githooks"' in setup
    assert "pre-commit" in setup
    assert "pre-push" in setup
    assert "core.hooksPath" in postinstall
    assert package["scripts"]["hooks:setup"]
    assert package["scripts"]["docs:sync"]
    assert package["scripts"]["docs:check"]
