"""_registry_taxonomy.py — Layer/scope/agent taxonomy maps and post-processing.

Imports REGISTRY from _registry_entries and mutates entries in-place
to inject layer, scope, agent, stability, and layer_group metadata.

Internal module: import vía tool_registry, not directly.
"""
from __future__ import annotations

from _registry_entries import REGISTRY  # noqa: F401 — re-exported

# ── Taxonomía de capas ─────────────────────────────────────────────────────────

LAYERS: dict[str, dict] = {
    "ejecución": {"icon": "⚡", "label": "EJECUCIÓN",  "desc": "ejecutar y avanzar trabajo activo"},
    "calidad":   {"icon": "🔍", "label": "CALIDAD",    "desc": "calidad de código del proyecto"},
    "salud":     {"icon": "💚", "label": "SALUD",      "desc": "salud y mantenimiento del framework"},
    "analítica": {"icon": "📊", "label": "ANALÍTICA",  "desc": "métricas, insights y patrones"},
    "visual":    {"icon": "🎨", "label": "VISUAL",     "desc": "generación de assets e interfaces"},
    "avanzado":  {"icon": "🔧", "label": "AVANZADO",   "desc": "herramientas avanzadas e integraciones"},
}

_LAYER_MAP: dict[str, str] = {
    # EJECUCIÓN
    "auto": "ejecución",
    "autonomy": "ejecución",
    "build-run": "ejecución",
    "done": "ejecución",
    "flow": "ejecución",
    "focus-mode": "ejecución",
    "goals": "ejecución",
    "ideas": "ejecución",
    "log-viewer": "ejecución",
    "menu": "ejecución",
    "next": "ejecución",
    "reopen": "ejecución",
    "script-runner": "ejecución",
    "select": "ejecución",
    "session": "ejecución",
    "sprint": "ejecución",
    "start": "ejecución",
    "task": "ejecución",
    "template-gen": "ejecución",
    "workflow": "ejecución",
    # CALIDAD
    "canon": "calidad",
    "code-search": "calidad",
    "debt": "calidad",
    "deps": "calidad",
    "doc-agent": "calidad",
    "doc-index": "calidad",
    "docs": "calidad",
    "hardcode": "calidad",
    "lint-runner": "calidad",
    "naming": "calidad",
    "orphan-shield": "calidad",
    "orphans": "calidad",
    "placeholder_scan": "calidad",
    "review": "calidad",
    "risk": "calidad",
    "rubber-duck": "calidad",
    "secrets": "calidad",
    "size-check": "calidad",
    "spanish": "calidad",
    "types": "calidad",
    # SALUD
    "audit": "salud",
    "build-clean": "salud",
    "config-check": "salud",
    "context": "salud",
    "deactivate": "salud",
    "heal-paths": "salud",
    "health": "salud",
    "neural-toolbox": "salud",
    "ping-server": "salud",
    "preflight-check": "salud",
    "project": "salud",
    "repo": "salud",
    "scope": "salud",
    "siembra": "salud",
    "sync": "salud",
    "validate": "salud",
    # ANALÍTICA
    "artifact-counter": "analítica",
    "chronicle": "analítica",
    "code-metrics": "analítica",
    "dashboard": "analítica",
    "diff": "analítica",
    "habit": "analítica",
    "insights": "analítica",
    "project-summary": "analítica",
    "recent-projects": "analítica",
    "recientes": "analítica",
    "search-history": "analítica",
    "snapshot": "analítica",
    "status": "analítica",
    "weekly-report": "analítica",
    "work_matrix": "analítica",
    # VISUAL
    "ableton-template": "visual",
    "banner": "visual",
    "agent-config": "visual",
    "create": "visual",
    "html-export": "visual",
    "hub": "visual",
    "image-studio": "visual",
    "image_gen": "visual",
    "launch": "visual",
    "sprite-studio": "visual",
    # AVANZADO
    "advisor": "avanzado",
    "agent": "avanzado",
    "alias-manager": "avanzado",
    "ask": "avanzado",
    "assign": "avanzado",
    "autonomous": "avanzado",
    "benchmark": "avanzado",
    "cabinet": "avanzado",
    "db": "avanzado",
    "devmode": "avanzado",
    "env-manager": "avanzado",
    "find-tool": "avanzado",
    "git-status": "avanzado",
    "hello": "avanzado",
    "inbox": "avanzado",
    "install": "avanzado",
    "llm": "avanzado",
    "llm-node": "avanzado",
    "lsp": "avanzado",
    "music": "avanzado",
    "net-scan": "avanzado",
    "neural": "avanzado",
    "notify-bago": "avanzado",
    "notify-desktop": "avanzado",
    "notify-whatsapp": "avanzado",
    "npath": "avanzado",
    "orchestrate": "avanzado",
    "peer": "avanzado",
    "personality-panel": "avanzado",
    "research": "avanzado",
    "route": "avanzado",
    "rules": "avanzado",
    "seed": "avanzado",
    "setup": "avanzado",
    "skill": "avanzado",
    "spiral": "avanzado",
    "spiral-agent": "avanzado",
    "state-manager": "avanzado",
    "toolsmith": "avanzado",
    "version": "avanzado",
    "why": "avanzado",
    "workflow-navigator": "avanzado",
    "workspace-select": "avanzado",
}

_SCOPE_MAP: dict[str, str] = {
    # framework — opera sobre el propio framework BAGO
    "advisor": "framework",
    "alias-manager": "framework",
    "artifact-counter": "framework",
    "auto": "framework",
    "banner": "framework",
    "benchmark": "framework",
    "cabinet": "framework",
    "config-check": "framework",
    "db": "framework",
    "devmode": "framework",
    "env-manager": "framework",
    "health": "framework",
    "hello": "framework",
    "install": "framework",
    "launch": "framework",
    "menu": "framework",
    "neural": "framework",
    "neural-toolbox": "framework",
    "notify-bago": "framework",
    "notify-desktop": "framework",
    "notify-whatsapp": "framework",
    "npath": "framework",
    "orphans": "framework",
    "personality-panel": "framework",
    "rules": "framework",
    "scope": "framework",
    "seed": "framework",
    "setup": "framework",
    "siembra": "framework",
    "state-manager": "framework",
    "sync": "framework",
    "toolsmith": "framework",
    "validate": "framework",
    "weekly-report": "framework",
    "work_matrix": "framework",
    "workspace-select": "framework",
    # project — opera sobre el proyecto activo
    "ableton-template": "project",
    "build-clean": "project",
    "build-run": "project",
    "canon": "project",
    "code-metrics": "project",
    "code-search": "project",
    "debt": "project",
    "deps": "project",
    "doc-index": "project",
    "docs": "project",
    "git-status": "project",
    "hardcode": "project",
    "heal-paths": "project",
    "html-export": "project",
    "image-studio": "project",
    "image_gen": "project",
    "lint-runner": "project",
    "log-viewer": "project",
    "lsp": "project",
    "music": "project",
    "naming": "project",
    "orphan-shield": "project",
    "placeholder_scan": "project",
    "review": "project",
    "risk": "project",
    "script-runner": "project",
    "secrets": "project",
    "size-check": "project",
    "snapshot": "project",
    "sprite-studio": "project",
    "template-gen": "project",
    "types": "project",
    # both — opera sobre el framework Y/O proyectos
    "agent": "both",
    "ask": "both",
    "assign": "both",
    "audit": "both",
    "autonomous": "both",
    "autonomy": "both",
    "chronicle": "both",
    "context": "both",
    "dashboard": "both",
    "deactivate": "both",
    "diff": "both",
    "doc-agent": "both",
    "done": "both",
    "find-tool": "both",
    "flow": "both",
    "focus-mode": "both",
    "agent-config": "both",
    "goals": "both",
    "habit": "both",
    "create": "both",
    "hub": "both",
    "ideas": "both",
    "inbox": "both",
    "insights": "both",
    "llm": "both",
    "llm-node": "both",
    "net-scan": "both",
    "next": "both",
    "orchestrate": "both",
    "peer": "both",
    "ping-server": "both",
    "preflight-check": "both",
    "project": "both",
    "project-summary": "both",
    "recent-projects": "both",
    "recientes": "both",
    "reopen": "both",
    "repo": "both",
    "research": "both",
    "route": "both",
    "rubber-duck": "both",
    "search-history": "both",
    "select": "both",
    "session": "both",
    "skill": "both",
    "spanish": "both",
    "spiral": "both",
    "spiral-agent": "both",
    "sprint": "both",
    "start": "both",
    "status": "both",
    "task": "both",
    "version": "both",
    "why": "both",
    "workflow": "both",
    "workflow-navigator": "both",
}

# ── Agent map — qué agente interno es responsable de cada comando ──────────────
# Agentes disponibles (ver .bago/roles/):
#   ANALISTA · ARQUITECTO · GENERADOR · ORGANIZADOR · VALIDADOR (produccion)
#   AUDITOR_CANONICO · CENTINELA_SINCERIDAD · VERTICE             (supervision)
#   REVISOR_SEGURIDAD · REVISOR_PERFORMANCE · REVISOR_UX          (especialistas)
#   INTEGRADOR_REPO                                                (especialistas)
_AGENT_MAP: dict[str, str] = {
    # ANALISTA — Análisis estático, detección, métricas, búsqueda
    "artifact-counter": "ANALISTA",
    "code-metrics": "ANALISTA",
    "code-search": "ANALISTA",
    "context": "ANALISTA",
    "debt": "ANALISTA",
    "deps": "ANALISTA",
    "diff": "ANALISTA",
    "find-tool": "ANALISTA",
    "habit": "ANALISTA",
    "insights": "ANALISTA",
    "lsp": "ANALISTA",
    "naming": "ANALISTA",
    "research": "ANALISTA",
    "review": "ANALISTA",
    "risk": "ANALISTA",
    "scope": "ANALISTA",
    "search-history": "ANALISTA",
    "snapshot": "ANALISTA",
    "types": "ANALISTA",
    "why": "ANALISTA",
    "work_matrix": "ANALISTA",
    # ARQUITECTO — Flujo, automatización, planificación, clonado
    "agent": "ARQUITECTO",
    "alias-manager": "ARQUITECTO",
    "auto": "ARQUITECTO",
    "autonomous": "ARQUITECTO",
    "autonomy": "ARQUITECTO",
    "cabinet": "ARQUITECTO",
    "devmode": "ARQUITECTO",
    "env-manager": "ARQUITECTO",
    "flow": "ARQUITECTO",
    "focus-mode": "ARQUITECTO",
    "hub": "ARQUITECTO",
    "inbox": "ARQUITECTO",
    "llm": "ARQUITECTO",
    "llm-node": "ARQUITECTO",
    "music": "ARQUITECTO",
    "net-scan": "ARQUITECTO",
    "neural": "ARQUITECTO",
    "neural-toolbox": "ARQUITECTO",
    "next": "ARQUITECTO",
    "npath": "ARQUITECTO",
    "orchestrate": "ARQUITECTO",
    "peer": "ARQUITECTO",
    "route": "ARQUITECTO",
    "seed": "ARQUITECTO",
    "siembra": "ARQUITECTO",
    "spiral": "ARQUITECTO",
    "spiral-agent": "ARQUITECTO",
    "state-manager": "ARQUITECTO",
    "toolsmith": "ARQUITECTO",
    "workflow-navigator": "ARQUITECTO",
    "workspace-select": "ARQUITECTO",
    # GENERADOR — Generación de artefactos, reportes, imágenes
    "ableton-template": "GENERADOR",
    "banner": "GENERADOR",
    "chronicle": "GENERADOR",
    "doc-index": "GENERADOR",
    "docs": "GENERADOR",
    "html-export": "GENERADOR",
    "image-studio": "GENERADOR",
    "image_gen": "GENERADOR",
    "notify-bago": "GENERADOR",
    "notify-desktop": "GENERADOR",
    "notify-whatsapp": "GENERADOR",
    "sprite-studio": "GENERADOR",
    "template-gen": "GENERADOR",
    "weekly-report": "GENERADOR",
    # ORGANIZADOR — Sprint, workflow, sesión, estado, repos, DB
    "ask": "ORGANIZADOR",
    "assign": "ORGANIZADOR",
    "agent-config": "ORGANIZADOR",
    "benchmark": "ORGANIZADOR",
    "build-run": "ORGANIZADOR",
    "create": "ORGANIZADOR",
    "dashboard": "ORGANIZADOR",
    "db": "ORGANIZADOR",
    "done": "ORGANIZADOR",
    "goals": "ORGANIZADOR",
    "ideas": "ORGANIZADOR",
    "log-viewer": "ORGANIZADOR",
    "menu": "ORGANIZADOR",
    "personality-panel": "ORGANIZADOR",
    "project": "ORGANIZADOR",
    "project-summary": "ORGANIZADOR",
    "recent-projects": "ORGANIZADOR",
    "recientes": "ORGANIZADOR",
    "reopen": "ORGANIZADOR",
    "repo": "ORGANIZADOR",
    "script-runner": "ORGANIZADOR",
    "select": "ORGANIZADOR",
    "session": "ORGANIZADOR",
    "setup": "ORGANIZADOR",
    "skill": "ORGANIZADOR",
    "sprint": "ORGANIZADOR",
    "status": "ORGANIZADOR",
    "sync": "ORGANIZADOR",
    "task": "ORGANIZADOR",
    "version": "ORGANIZADOR",
    "workflow": "ORGANIZADOR",
    # VALIDADOR — Salud, validación, diagnóstico
    "audit": "VALIDADOR",
    "build-clean": "VALIDADOR",
    "canon": "VALIDADOR",
    "config-check": "VALIDADOR",
    "deactivate": "VALIDADOR",
    "doc-agent": "VALIDADOR",
    "git-status": "VALIDADOR",
    "heal-paths": "VALIDADOR",
    "health": "VALIDADOR",
    "lint-runner": "VALIDADOR",
    "orphan-shield": "VALIDADOR",
    "orphans": "VALIDADOR",
    "ping-server": "VALIDADOR",
    "placeholder_scan": "VALIDADOR",
    "preflight-check": "VALIDADOR",
    "size-check": "VALIDADOR",
    "validate": "VALIDADOR",
    # CENTINELA_SINCERIDAD — Integridad de commits y sinceridad
    "hardcode": "CENTINELA_SINCERIDAD",
    "rubber-duck": "CENTINELA_SINCERIDAD",
    "spanish": "CENTINELA_SINCERIDAD",
    # AUDITOR_CANONICO — Reglas y auditoría canónica
    "rules": "AUDITOR_CANONICO",
    # REVISOR_SEGURIDAD — Seguridad y secretos
    "secrets": "REVISOR_SEGURIDAD",
    # REVISOR_PERFORMANCE — Rendimiento y experiencia operativa
    "advisor": "REVISOR_PERFORMANCE",
    "launch": "REVISOR_PERFORMANCE",
    # VERTICE — Gobierno del sistema, entrada, instalación
    "hello": "VERTICE",
    "install": "VERTICE",
    "start": "VERTICE",
}

# ── Inject layer + scope + agent into each REGISTRY entry ─────────────────────

for _cmd, _entry in REGISTRY.items():
    if not _entry.layer:
        _entry.layer = _LAYER_MAP.get(_cmd, "avanzado")
    if not _entry.scope:
        _entry.scope = _SCOPE_MAP.get(_cmd, "both")
    if not _entry.agent:
        _entry.agent = _AGENT_MAP.get(_cmd, "ORGANIZADOR")

# ── Kernel Lockdown classification (v3.2) ─────────────────────────────────────

_CORE_CMDS: frozenset[str] = frozenset({
    "health", "audit", "status", "task", "session", "flow",
    "project", "sync", "scope", "secrets", "validate", "context",
})
_DANGEROUS_CMDS: frozenset[str] = frozenset({
    "install", "autonomous", "orchestrate", "cabinet", "peer", "db", "auto", "spiral",
})
_INTERNAL_CMDS: frozenset[str] = frozenset({
    "banner", "hello", "hub", "start", "done",
})
_LAYER_GROUP_MAP: dict[str, str] = {
    # core public interface
    "health": "core",
    "status": "core",
    "validate": "core",
    "audit": "core",
    "task": "core",
    "flow": "core",
    "session": "core",
    "project": "core",
    "context": "core",
    "sync": "core",
    "scope": "core",
    "secrets": "core",
    # agents
    "llm": "agents",
    "route": "agents",
    "autonomous": "agents",
    "auto": "agents",
    "ask": "agents",
    "research": "agents",
    "chronicle": "agents",
    # ui
    "hub": "ui",
    "dashboard": "ui",
    "peer": "ui",
    # labs
    "image-studio": "labs",
    "sprite-studio": "labs",
    "image_gen": "labs",
    "music": "labs",
    "ableton-template": "labs",
}

for _cmd, _entry in REGISTRY.items():
    if _entry.deprecated:
        _entry.stability = "legacy"
    elif _cmd in _CORE_CMDS:
        _entry.stability = "core"
        _entry.preflight_policy = "required"
    elif _cmd in _DANGEROUS_CMDS:
        _entry.stability = "dangerous"
        _entry.risk = "dangerous"
    elif _cmd in _INTERNAL_CMDS:
        _entry.stability = "internal"
        _entry.preflight_policy = "none"
    # else: stability="experimental", risk="safe", preflight_policy="optional" (defaults)
    _entry.layer_group = _LAYER_GROUP_MAP.get(_cmd, _entry.layer_group)

# ── Visual badges ──────────────────────────────────────────────────────────────

SCOPE_BADGE: dict[str, str] = {
    "framework": "🔵",
    "project":   "🟢",
    "both":      "⚪",
}
