from __future__ import annotations

# Cada entrada: (nombre_grupo, [(cmd, descripción_corta, descripción_larga)])
MENU: list[tuple[str, list[tuple[str, str, str]]]] = [
    ("🚀  Sesión", [
        ("start",            "Arranca sesión BAGO",          "Panel visual completo: health, workspace, tarea activa, ideas priorizadas"),
        ("status",           "Estado actual del sistema",    "Flujo activo + tarea pendiente + health score en 3 líneas"),
        ("hello",            "Bienvenida y contexto",        "Resumen de estado: workflow, sprint, voces CAP activas"),
        ("next",             "Siguiente idea → tarea",       "Toma la idea top del backlog y abre una tarea de trabajo"),
        ("devmode",          "Dev / User mode toggle",       "Developer: vista framework completa. User: vista project-first limpia"),
        ("workspace-select", "Elige espacio de trabajo",     "Menú: framework (self) | directorio padre | ruta externa. Persiste en repo_context.json"),
        ("recent-projects",  "Proyectos recientes",          "Historial de repos visitados con sesiones e ideas implementadas"),
    ]),
    ("💡  Ideas", [
        ("ideas",   "Ver backlog priorizado",       "Lista ideas ordenadas por contexto, sprint y urgencia", [
            ("",           "(lista)",      "Muestra las top 5-20 ideas priorizadas por contexto (predeterminado)"),
            ("--select",   "--select",     "Selector interactivo del backlog con navegación"),
            ("--baseline", "--baseline",   "Solo ideas de bajo riesgo, estables y probadas"),
            ("--export",   "--export",     "Exporta snapshot de ideas a .bago/state/ideas_snapshot.md"),
            ("--health",   "--health",     "Estadísticas del catálogo: total, por estado, por intención"),
            ("--all",      "--all",        "Muestra ideas de todos los proyectos (ignora filtro devmode)"),
        ]),
        ("cosecha", "Capturar nueva idea",          "Registra una idea nueva en bago.db con título, contexto y prioridad"),
        ("next",    "Aceptar idea top como tarea",  "Shortcut: toma la idea #1 y la convierte en tarea activa"),
        ("assign",  "Asignar idea a tarea",         "Convierte una idea específica en la tarea activa del sprint"),
        ("select",  "Seleccionar idea del backlog", "Navegación interactiva del backlog con filtros"),
        ("inbox",   "Bandeja de entrada",           "Ideas capturadas sin clasificar pendientes de triaje"),
        ("promote", "Promover idea a sprint",       "Sube una idea al sprint activo con prioridad ajustada"),
        ("reopen",  "Reabrir tarea cerrada",        "Reabre una tarea done para revisión o continuación"),
    ]),
    ("📋  Tarea activa", [
        ("task",     "Ver tarea actual",     "Muestra la tarea activa: idea, contexto, pasos pendientes"),
        ("done",     "Cerrar tarea actual",  "Registra la tarea como completada con evidencia"),
        ("workflow", "Gestionar workflow",   "Inicia, avanza o cierra el workflow activo del sprint"),
        ("flow",     "Estado del flujo",     "Vista del grafo de workflow: nodos, transiciones, estado"),
        ("sprint",   "Panel del sprint",     "Resumen del sprint: ideas completadas, velocidad, próximos"),
        ("goals",    "Objetivos del sprint", "Define y revisa los objetivos cualitativos del sprint"),
        ("scope",    "Scope de la tarea",    "Define qué archivos/módulos están en scope para esta tarea"),
    ]),
    ("✅  Calidad & Salud", [
        ("health",    "Score de salud 0-100",        "5 dimensiones: integridad, disciplina, decisiones, stale, consistencia", [
            ("",            "score",       "Score 0-100 ponderado (predeterminado)"),
            ("report",      "report",      "Reporte completo Markdown/HTML con todos los checks"),
            ("stability",   "stability",   "Diagnóstico completo de estabilidad del workspace"),
            ("efficiency",  "efficiency",  "Ratio de eficiencia inter-versiones del framework"),
            ("consistency", "consistency", "Anti-drift: verifica que registry/CI/README son coherentes"),
            ("sincerity",   "sincerity",   "Detecta promesas vacías y sycofancía en docs y sesiones"),
        ]),
        ("validate",  "Validación completa",         "GO/FAIL en manifest, state y pack — ejecutar antes de cada commit", [
            ("",         "(completo)",  "Validación completa: manifest + state + pack (predeterminado)"),
            ("manifest", "manifest",    "Solo valida pack.json contra global_state.json"),
            ("state",    "state",       "Solo valida coherencia de global_state.json y sesiones"),
            ("contents", "contents",    "Valida un ZIP de pack distribuible (pack_contents)"),
        ]),
        ("audit",     "Auditoría de sesión",         "Trail completo: roles, contratos, evidencias, decisiones"),
        ("stale",     "Detectar estado obsoleto",    "Encuentra workflows abandonados, tareas huérfanas, state desincronizado"),
        ("sincerity", "Detector de promesas vacías", "Analiza si el agente cumplió lo que prometió en la sesión"),
        ("stability", "Informe de estabilidad",      "Tendencia histórica del health score con alertas de regresión"),
        ("siembra",   "Semillas de mejora",          "Registra aprendizajes de la sesión como semillas para ideas futuras"),
        ("heal",      "Reparar inconsistencias",     "Auto-repair de problemas detectados por health/validate"),
        ("orphan-shield", "Escudo anti-huérfanos",   "Detecta 4 tipos de artefactos huérfanos: archivos, registry, rutas, docs"),
        ("doc-index",     "Índice documental",       "Índice reverso: qué documentos cubren qué herramientas"),
        ("canon",          "Bucle de Shepard",         "4 modos x 3 voces: MODULAR/SCAN/CREATE/EVOLVE · ciclo completo de salud"),
    ]),
    ("🔍  Análisis de código", [
        ("code-metrics", "Métricas del código",      "Complejidad ciclomática, duplicaciones, líneas por módulo"),
        ("code-search",  "Búsqueda semántica",       "Busca en el historial de código del proyecto con contexto"),
        ("lint-runner",  "Linter configurable",      "Ejecuta pyflakes/ruff/eslint según el tipo de proyecto"),
        ("rubber-duck",  "Debug asistido",           "Explica el problema en voz alta — el sistema hace preguntas"),
        ("naming",       "Check de nomenclatura",    "Verifica convenciones de nombres en el codebase"),
        ("hardcode",     "Detectar hardcoding",      "Encuentra valores hardcodeados que deberían ser config"),
        ("secrets",      "Auditoría de secretos",    "Detecta API keys, passwords y tokens en el código"),
        ("deps",         "Análisis de dependencias", "Estado de dependencias: outdated, vulnerables, no usadas"),
    ]),
    ("🤖  Agentes & IA", [
        ("agent",          "Gateway de agentes",   "Lanza y coordina agentes especializados del sistema BAGO"),
        ("autonomous",     "Bucle autónomo",       "Ejecuta ciclos autónomos de mejora sin intervención humana"),
        ("neural",         "Motor neural",         "Bus de mensajes SSE inter-agente: nodos, mapas, estado"),
        ("neural-toolbox", "Toolbox adaptativo",   "Convierte contexto en lenguaje natural a un toolbox configurado"),
        ("llm",            "Configuración LLM",    "Gestiona el modelo activo, temperatura y parámetros del LLM"),
        ("advisor",        "Consejero estratégico","Recomendaciones de next steps basadas en el estado del sistema"),
        ("toolsmith",      "Creador de tools",     "Genera nuevas herramientas BAGO desde especificación en lenguaje natural"),
        ("route",          "Router de intención",  "Mapea texto libre a comandos BAGO: 'quiero ver mis ideas' → bago ideas"),
    ]),
    ("📁  Workspace & Repos", [
        ("repo-clone",  "Clonar repositorio",    "Clona un repo GitHub en el workspace con auto-setup BAGO"),
        ("repo-list",   "Listar repos clonados", "Lista repositorios en el workspace con estado y health"),
        ("repo-switch", "Cambiar repo activo",   "Cambia el contexto activo entre repositorios del workspace"),
        ("git",         "Contexto git",          "Detect, map, git status, stale — vista git del workspace"),
        ("git-status",  "Estado git detallado",  "Estado completo: branch, staged, unstaged, remotes"),
        ("project",     "Gestión de proyecto",   "Crea, vincula o consulta el estado del proyecto activo"),
        ("context",     "Detector de contexto",  "Identifica automáticamente el tipo de proyecto y sugiere workflow"),
        ("map",         "Mapa del workspace",    "Vista estructural completa del workspace y sus relaciones"),
    ]),
    ("📊  Informes & Conocimiento", [
        ("weekly-report",  "Informe semanal",       "Resumen de la semana: ideas implementadas, salud, velocidad"),
        ("recientes",      "Actividad reciente",    "Commits, sesiones e ideas de los últimos N días"),
        ("snapshot",       "Snapshot del estado",   "Captura y compara snapshots del estado del sistema", [
            ("",        "(comparar)",  "Compara los dos últimos snapshots (predeterminado)"),
            ("--list",  "--list",      "Lista todos los snapshots guardados con fecha y tamaño"),
            ("--ideas", "--ideas",     "Compara solo la sección de ideas entre snapshots"),
            ("--tools", "--tools",     "Compara solo la sección de herramientas entre snapshots"),
            ("--json",  "--json",      "Salida de la comparación en formato JSON"),
        ]),
        ("dashboard",      "Panel principal",       "Dashboard interactivo con todas las métricas del sistema"),
        ("work_matrix",    "Matriz de trabajo",     "Visualiza el trabajo por agente, capa y tipo de tarea"),
        ("search-history", "Búsqueda en historial", "Busca en el historial completo de sesiones BAGO"),
        ("docs",           "Documentación generada","Documentación auto-generada de todos los comandos activos"),
        ("chronicle",      "Crónica del proyecto",  "Historia narrativa del proyecto: decisiones, hitos, aprendizajes"),
    ]),
    ("⚙️  Configuración", [
        ("devmode",           "Dev / User mode",    "Alterna entre vista de framework completa y vista de proyecto"),
        ("alias-manager",     "Gestión de alias",   "Crea, edita y elimina alias personalizados para comandos"),
        ("env-manager",       "Variables de entorno","Gestiona .env del proyecto con validación y diff"),
        ("personality-panel", "Perfil del agente",  "Configura el tono, verbosidad y estilo del agente BAGO"),
        ("version",           "Versión del sistema","Versión actual de BAGO con changelog y notas de upgrade"),
        ("setup",             "Configuración inicial","Wizard de configuración inicial de BAGO en un nuevo sistema"),
        ("install",           "Instalar BAGO",      "Instala BAGO en un repositorio externo"),
    ]),
    ("🛠️  Infraestructura", [
        ("net-scan",      "Escaneo de red",      "Descubre puertos y servicios activos en la red local"),
        ("ping-server",   "Check de servicio",   "Verifica disponibilidad y latencia de un endpoint"),
        ("state-manager", "Gestor de estado",    "Split, materialize y merge del estado por capas"),
        ("seed",          "Semillas del sistema", "Gestiona las semillas de conocimiento del motor BAGO"),
        ("notify-desktop","Notificación desktop", "Envía notificación al sistema operativo"),
        ("notify-bago",   "Notificación BAGO",   "Envía notificación interna al sistema de presencia"),
        ("build-clean",   "Limpiar build",       "Elimina artefactos de build: __pycache__, dist, .eggs"),
        ("build-run",     "Ejecutar build",      "Ejecuta el pipeline de build del proyecto activo"),
    ]),
]
