name: njsscan sarif

on:
  push:
    branches: ["master", "main", "windows", "android", "release/**"]
  pull_request:
    branches: ["master", "main"]
  schedule:
    - cron: "25 5 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  njsscan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fail-fast sentinel
        if: ${{ false }}
        shell: bash
        run: |
          exit 1
      - name: Scan JavaScript
        uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
        with:
          args: ". --sarif --output results.sarif || true"
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
